export { default as TopInstructionCard } from './top-instruction-card'
export { default as Main } from './main'
export { default as Footer } from './footer'
export { default as PrivacyModal } from './privacy-modal'
export { default as NoMobileSupport } from './no-mobile-support'
